---
title: "p8105_hw1_aw3253"
author: Alyssa W. 
output: github_document
---


# Problem 1

```{r}
library(tidyverse)

plot_df = tibble(
  vec_numeric = rnorm(10),
  vec_char = c("D", "A", "T", "A", "S", "C", "I", "E", "N", "C"),
  vec_logical = c(TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
  vec_factor = factor(c("underweight", "overweight", "obese", "obese", "obese", "underweight", "underweight", "obese", "underweight", "underweight"))
)

```

### Finding the mean

```{r}
library(tidyverse)
mean(pull(plot_df, var = vec_numeric))
mean(pull(plot_df, var = vec_char))
mean(pull(plot_df, var = vec_logical))
mean(pull(plot_df, var = vec_factor))

```


# Problem 2
```{r, echo=FALSE}
install.packages("palmerpenguins")

```


```{r}
data("penguins", package = "palmerpenguins")

```

This data has The data frame has `r nrow(penguins)` rows and `r ncol(penguins)`. The mean flipper length is `r mean(penguins)`.


### Scatterplot 
```{r}
new = ggplot(penguins, aes(x = bill_length_mm, y=flipper_length_mm)) + geom_point()

```